### ISSUE TITLE
android termux install errors

### ISSUE THREAD

**Issue by develperbayman** [thanhsonng/chatgpt-voice#10]
idk maybe im missing something

~ $ git clone https://github.com/thanhsonng/chatgpt-voice.git
cd chatgpt-voice
npm run install
npm run dev
Cloning into 'chatgpt-voice'...
remote: Enumerating objects: 508, done.
remote: Counting objects: 100% (508/508), done.
remote: Compressing objects: 100% (262/262), done.
remote: Total 508 (delta 295), reused 436 (delta 230), pack-reused 0
Receiving objects: 100% (508/508), 948.07 KiB | 2.53 MiB/s, done.
Resolving deltas: 100% (295/295), done.
npm ERR! Missing script: "install"
npm ERR! 
npm ERR! Did you mean this?
npm ERR!     npm uninstall # Remove a package
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2023-03-28T02_08_20_324Z-debug-0.log

> chatgpt-voice@0.0.0 dev
> vite

sh: 1: vite: not found

**Comment by develperbayman** [comment]
0 verbose cli /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/bin/npm
1 info using npm@9.4.0
2 info using node@v19.6.1
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 8ms
5 timing config:load:file:/data/data/com.termux/files/usr/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/data/data/com.termux/files/home/chatgpt-voice/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/data/data/com.termux/files/home/.npmrc Completed in 2ms
12 timing config:load:user Completed in 3ms
13 timing config:load:file:/data/data/com.termux/files/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 2ms
16 timing config:load Completed in 30ms
17 timing npm:load:configload Completed in 31ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm run install
21 verbose argv "run" "install"
22 timing npm:load:setTitle Completed in 3ms
23 timing config:load:flatten Completed in 6ms
24 timing npm:load:display Completed in 9ms
25 verbose logfile logs-max:10 dir:/data/data/com.termux/files/home/.npm/_logs/2023-03-28T02_08_20_324Z-
26 verbose logfile /data/data/com.termux/files/home/.npm/_logs/2023-03-28T02_08_20_324Z-debug-0.log
27 timing npm:load:logFile Completed in 10ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 60ms
31 silly logfile done cleaning log files
32 timing command:run Completed in 43ms
33 verbose stack Error: Missing script: "install"
33 verbose stack
33 verbose stack Did you mean this?
33 verbose stack     npm uninstall # Remove a package
33 verbose stack
33 verbose stack To see a list of scripts, run:
33 verbose stack   npm run
33 verbose stack     at RunScript.run (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/commands/run-script.js:99:13)
33 verbose stack     at async module.exports (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/cli.js:134:5)
34 verbose cwd /data/data/com.termux/files/home/chatgpt-voice
35 verbose Linux 5.10.66
36 verbose node v19.6.1
37 verbose npm  v9.4.0
38 error Missing script: "install"
38 error
38 error Did you mean this?
38 error     npm uninstall # Remove a package
38 error
38 error To see a list of scripts, run:
38 error   npm run
39 verbose exit 1
40 timing npm Completed in 146ms
41 verbose code 1
42 error A complete log of this run can be found in:
42 error     /data/data/com.termux/files/home/.npm/_logs/2023-03-28T02_08_20_324Z-debug-0.log

**Comment by sonngdev** [comment]
Sorry for the typo, it should be `npm install`, not `npm run install`. I will update the README
