### ISSUE TITLE
Failed to get the response, please try again.

### ISSUE THREAD

**Issue by CasperOng** [thanhsonng/chatgpt-voice#4]

**Comment by sonngdev** [comment]
Thanks for the issue, the server can be quite unstable especially when ChatGPT is restricting usage so much. I've resolved this issue.

**Comment by CasperOng** [comment]
@thanhsonng It doesn't work again. Please reopen the issue. Also could you provide more reason and fixes for this issue? Since I want to self host it and am afraid this issue will appear again.
