### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by helperAI** [thanhsonng/chatgpt-voice#6]
I tried https://chatgpt.sonng.dev/. 
Failed to get the response, please try again.

Can you make it work again? pls

BTW, can you upgrade the chatgpt-api to version 4 which use the openai key instead of user email and password? tks

**Comment by Mrzhang-hub** [comment]
Also meet the same problem. When can this be fixed?

**Comment by sonngdev** [comment]
My apology, the server is quite unstable because ChatGPT has strict limitations to bot activities, so it regularly disconnects. I have yet to find a solution for it, in the meantime, I will have to periodically check for server health and restart it when needed.

**Comment by sonngdev** [comment]
I have upgraded the backend API to use official ChatGPT APIs. This problem should be resolved now 🎉
